<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Laminas\Escaper\Escaper $escaper */
?>
<span class="header-checkout">
    <a href="<?=$escaper->escapeHtml($block->getHref())?>"
       title="<?=$escaper->escapeHtml(__("Return to Cart"))?>"
        alt="<?=$escaper->escapeHtml(__("Return to Cart"))?>" >
        <?=$escaper->escapeHtml(__("Return to Cart"))?>
    </a>
</span>
